title:              MINLOG
email:              riven3069@naver.com
description:        
author:             MinHyun-Code
baseurl:            ""
url:                "https://minhyun-code.github.io"
asset_url:          /assets

# Social Profiles
twitter_username:   
github_username:    MinHyun-Code
facebook_username:  
instagram_username: an_min96
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  
category_list: [java, jpa, algorithm, javascript, typescript, vue.js, sql, aws, linux, windows, blog, etc]

# Code highlighter
highlighter: rouge

gems:
    - jekyll-paginate-v2

pagination:
    enabled: true
    sort_field: 'date'
    sort_reverse: true