title:              MINLOG
email:              riven3069@naver.com
description:        
author:             MinHyun-Code
baseurl:            "/blog"
url:                "https://MinHyun-Code.github.io/blog"

# Social Profiles
twitter_username:   
github_username:    MinHyun-Code
facebook_username:  
instagram_username: an_min96
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

category_list: [java, javascript, sql, aws, linux, windows, etc]

# Code highlighter
highlighter: rouge
